### ISSUE TITLE
Change Google Cloud

### ISSUE THREAD

**Issue by mhf-ir** [eclipse/open-vsx.org#201] opened 2020-11-05 07:58 UTC
Google block many people:
https://support.google.com/cloudidentity/answer/2891389?hl=en
Change hosting of it's not working for us. thats the bigger problem than microsft vs code telemntry.

![Screenshot from 2020-11-05 11-30-17](https://user-images.githubusercontent.com/1172526/98213441-534cec80-1f5a-11eb-8a94-a28a92ed577d.png)

Politics sucks if your plane is freedom get rid of Google platform.

**Comment by spoenemann** [comment] 2020-11-05 09:30
Duplicate of #39.

**Closed by spoenemann** 2020-11-05 09:30 UTC
