### ISSUE TITLE
openvsx.org is not accessible in countries like Iran (403 forbidden)

### ISSUE THREAD

**Issue by HKalbasi** [eclipse/open-vsx.org#77] opened 2020-06-26 18:58 UTC
It shows a broken robot with a google logo and a 403 response code. And vscodium can not find extensions. It's a common scenario in countries that U.S. sanctioned them, like Iran, Cuba, Crimea region, North Korea, Sudan, ... .

I don't think U.S. regime puts restriction on downloading vscode extensions, because microsoft registry of vscode is accessible here.

Please consider talking with google, Or host this service (or a mirror of it) in something like Cloudflare that does not have such restrictions.

This issue is just an ethical advice. You can ruthlessly close this issue, And I completely understand that it could make economic and legal costs, But I think it is closer to "openness".

**Comment by spoenemann** [comment] 2020-07-13 10:09
Duplicate of #39.

I'm sorry for this. Probably it's due to restrictions made by Google Cloud. I don't know yet which cloud provider we will use after transferring the service to the Eclipse Foundation.

**Closed by spoenemann** 2020-07-13 10:09 UTC
